name:                orb
version:             0.1.0.0

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- sdl2
- sdl2-ttf

library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - containers
  - tagsoup
  - css-text
  - text
  - attoparsec
  - lens

executables:
  orb-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - orb
    - containers

tests:
  orb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - orb
    - hspec
    - containers
